/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import entidades.Area;
import entidades.Integrante;
import entidades.Lider;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel; //modelo de datos para JTable
import java.util.Vector; //se requiere para hacer filas
import javax.swing.JOptionPane;
import main.Test;

/**
 *
 * @author eterr
 */
public class JframeTabla extends javax.swing.JFrame {
    Area m = new Area("Desarrollo de Software");
    private Lider lider;
    //Se debe declarar el modelo de datos del JTable como una variable global
    DefaultTableModel modelo;

    /**
     * Creates new form frmVentana01
     */
    public JframeTabla() {
        initComponents();
    }

    public JframeTabla(Lider lider) {
        initComponents();
        this.lider=lider;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaGestor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BuscarjButton = new javax.swing.JButton();
        TextoBuscarjTextField = new javax.swing.JTextField();
        VerDetallejButton = new javax.swing.JButton();
        AgregarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TablaGestor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        TablaGestor.setSelectionBackground(new java.awt.Color(204, 153, 0));
        TablaGestor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaGestor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaGestor.setShowGrid(true);
        jScrollPane2.setViewportView(TablaGestor);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestor de Empleados");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BuscarjButton.setText("Buscar");
        BuscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarjButtonActionPerformed(evt);
            }
        });

        VerDetallejButton.setText("Ver detalle");
        VerDetallejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetallejButtonActionPerformed(evt);
            }
        });

        AgregarjButton.setText("Agregar");
        AgregarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(VerDetallejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AgregarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TextoBuscarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BuscarjButton))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerDetallejButton)
                    .addComponent(AgregarjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarjButton)
                    .addComponent(TextoBuscarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Inicializando el modelo de datos
        modelo = new DefaultTableModel(){
            //se requiere evitar la edición de las celdas del JTable
            public boolean isCellEditable(int rowIndex, int mColIndex)
            {
                return false; //permite el retorno falso indicando que no permita editar la celda
            }
        };

        //Poniendo columnas al modelo
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("DNI");

        //Colocando el modelo en el JTable
        TablaGestor.setModel(modelo);

        //Definiendo el ancho de las columnas
        TablaGestor.getColumnModel().getColumn(0).setMaxWidth(150);
        TablaGestor.getColumnModel().getColumn(0).setPreferredWidth(150);
        TablaGestor.getColumnModel().getColumn(1).setMaxWidth(80);
        TablaGestor.getColumnModel().getColumn(1).setPreferredWidth(80);
        TablaGestor.getColumnModel().getColumn(2).setMaxWidth(90);
        TablaGestor.getColumnModel().getColumn(2).setPreferredWidth(90);


        String []data = new String[3];
        data[0] = lider.getNombre();
        data[1] = lider.getEdad();
        data[2] = lider.getDni();
        modelo.addRow(data);

        for(Integrante i: lider.getArea().getIntegrantes()){
            data[0] = i.getNombre();
            data[1] = i.getEdad();
            data[2] = i.getDni();
            modelo.addRow(data);
        }

    }//GEN-LAST:event_formWindowOpened

    private void BuscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarjButtonActionPerformed
        String buscar = TextoBuscarjTextField.getText();

        // limpiando datos actuales
        int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }

        // obteniendo y agregando los resultados del filtro
        String[] data = new String[3];
        for(Integrante i: lider.getArea().getIntegrantes(buscar)){
            data[0] = i.getNombre();
            data[1] = i.getEdad();
            data[2] = i.getDni();
            modelo.addRow(data);
        }

    }//GEN-LAST:event_BuscarjButtonActionPerformed

    private void VerDetallejButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VerDetallejButtonActionPerformed
        int fila = TablaGestor.getSelectedRow();
        if (fila >= 0) {

            String DNI = modelo.getValueAt(fila, 2).toString();
            Integrante integrante = lider.getArea().getIntegrante(DNI);

            if (integrante != null) {

                Detalle detalle = new Detalle(integrante);
                detalle.setVisible(true);
                detalle.addWindowListener(new WindowAdapter() {

                    @Override
                    public void windowClosing(WindowEvent e) {
                        DetalleCerrando(detalle, DNI);
                    }
                });
                this.setVisible(false);
            }
        }
    }// GEN-LAST:event_VerDetallejButtonActionPerformed

    private void AgregarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarjButtonActionPerformed
        Detalle detalle = new Detalle(null);
        detalle.setVisible(true);
        detalle.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                DetalleCerrando(detalle, null);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_AgregarjButtonActionPerformed

    private void DetalleCerrando(Detalle detalle, String DNI) {
        int evento = detalle.getEvento();

        switch (evento) {
            case 1: // boton Modificar
                lider.getArea().modificarIntegrante(DNI, detalle.getIntegrante());

                CargarDatos();
                break;
            case 2: // boton Eliminar
                lider.getArea().eliminarIntegrante(DNI);

                CargarDatos();
                break;
            case 3: // boton Agregar
                lider.getArea().guardarIntegrante(detalle.getIntegrante());

                CargarDatos();
                break;
        }
        this.setVisible(true);
    }

    private void CargarDatos() {
        // Recargar lista de integrantes
        // Limpiar
        int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }

        // Cargando datos
        String[] data = new String[3];
        for (Integrante i : lider.getArea().getIntegrantes()) {
            data[0] = i.getNombre();
            data[1] = i.getEdad();
            data[2] = i.getDni();
            modelo.addRow(data);
        }
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        // Instanciar la clase JframeTabla a la clase main
        JframeTabla window = new JframeTabla();
        window.setTitle("Ventana utilizando JOptionPane");
        window.setVisible(true);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarjButton;
    private javax.swing.JButton BuscarjButton;
    private javax.swing.JTable TablaGestor;
    private javax.swing.JTextField TextoBuscarjTextField;
    private javax.swing.JButton VerDetallejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
